- hosts:            book02
  gather_facts:     yes
  strategy:         free
  become:           yes
  become_method:    sudo
  tasks:
  - block:
    - name:           Adding new repos
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /
        - deb http://repository.spotify.com stable non-free
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial main restricted
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial universe
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates universe
        - deb http://security.ubuntu.com/ubuntu xenial-security main restricted
        - deb http://security.ubuntu.com/ubuntu xenial-security multiverse
        - deb http://security.ubuntu.com/ubuntu xenial-security universe
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        - deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        - deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
        - deb http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu xenial main
        - deb-src http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu xenial main
        - deb https://deb.nodesource.com/node_9.x xenial main
        - deb-src https://deb.nodesource.com/node_9.x xenial main
        - deb http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial main
        - deb-src http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial main
        - deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial main
        - deb-src http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial main
    - name:           Checking and adding keys
      apt_key:
        keyserver:    keyserver.ubuntu.com
        id:           "{{ item }}"
      with_items:
        - EEA14886
        - 437D05B5
        - C0B21F32
        - EFE21092
        - FBB75451
        - 68576280
        - 341D9410
        - 557BEFF9
        - 038651BD
        - 0EBFCD88
        - 7BB9C367
        - 21C5F0BA
        - 341D9410
        - 0068FCD6
    - name:           Dist-upgrade
      apt:
        update_cache: yes
        upgrade:      dist
    - name:           Accepting fonts EULA for Wine installation
      shell:          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    - name:           Installing software
      apt:
        name:         "{{ item }}"
        state:        latest
      with_items:
        - nmap
        - wine
        - zenmap
        - firefox
        - chromium-browser
        - g++
        - gcc
        - nodejs
        - git
        - iotop
        - htop
        - iperf
        - ldap-utils
        - iperf3
        - iptraf-ng
        - python3.5
        - mysql-server
        - mysql-utilities
        - nginx
        - zabbix-agent
        - apache2-utils
        - smartmontools
        - openjdk-8-jre
        - icedtea-8-plugin
        - thunderbird
        - automake
        - btrfs-tools
        - bzip2
        - cifs-utils
        - gdebi
        - k4dirstat
        - python3-pip
        - php7*-cli
        - gstreamer1.0-libav
        - gstreamer1.0-fluendo-mp3
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-bad-videoparsers
        - gstreamer1.0-plugins-bad-faad
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-vaapi
        - docker.io
        - apt-transport-https
        - software-properties-common
        - pidgin
        - pidgin-sipe
        - ntfs-3g
        - nload
        - p7zip-full
        - openvpn
        - network-manager-openvpn
        - network-manager-pptp
        - sqlite3
        - snmp
        - qemu-system-arm
        - qemu-system-x86
        - libvirt0
        - libvirt-bin
        - virt-manager
        - python-samba
        - python-sqlite
        - python*pip
        - php7*bcmath
        - php7*dba
        - php7*fpm
        - tmux
        - xfsprogs
        - cryptsetup
        - spotify-client
        - freerdp-x11
        - remmina
        - deluge
        - apt-transport-https
        - ca-certificates
        - curl
        - python3-tk
        - software-properties-common
        - libsnmp-dev
        - atom
        - uncrustify
        - amdgpu-pro
        - composer
        - keepassxc
        - haskell-platform
        - ruby
    - name:           Installing node.js packages
      npm:
        name:         "{{ item }}"
        global:       yes
      with_items:
        - babel-cli
        - eslint-config-airbnb-base
        - eslint
        - babel-eslint
    - name:           Installing python packets
      pip:
        name:         "{{ item }}"
        executable:   pip3
        state:        latest
      with_items:
        - sqlparse
        - autopep8
        - beautysh
        - jupyter
        - numpy
        - ipaddress
        - pymysql
        - pysqlite3
        - pandas
        - uuid
        - z3
        - configparser
        - jsbeautifier
        - easysnmp
        - ping3
        - netaddr
    - name:           Installing atom modules
      shell:          "apm install {{ item }}"
      with_items:
        - linter
        - hydrogen
        - linter-php
        - linter-eslint
        - linter-pycodestyle
        - atom-ternjs
        - autocomplete-modules
        - js-hyperclick
        - linter-ui-default
        - intentions
        - busy-signal
        - platformio-ide-terminal
        - atom-beautify
        - minimap
        - color-picker
        - sort-lines
        - hyperclick
      become_user:    user100
      become:         true
    - name:           Download apps
      unarchive:
        src:          http://perminov.im/app.tgz
        dest:         /tmp
        remote_src:   yes
    - name:           Get PHP-CS-FIXER
      get_url:
        url:          http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
        dest:         /usr/bin/php-cs-fixer
    - name:           Set PHP-CS-FIXER Attribute
      file:
        path:         /usr/bin/php-cs-fixer
        mode:         "a+x"
    - name:           Install WmiClient
      apt:
        deb:          "/tmp/*.deb"
    - name:           Clean
      apt:
        autoclean:    yes
        autoremove:   yes
    - name:         VM Swapinnes
      sysctl:
        name:       vm.swappiness
        value:      1
        state:      present
        sysctl_set: yes
    - name:         Drop Cahes
      sysctl:
        name:       vm.drop_caches
        value:      3
        state:      present
        reload:     yes
        sysctl_set: yes
