- hosts:              book02
  # gather_facts:     yes
  strategy:           free
  become:             yes
  become_method:      sudo
  # vars:
    # release:        {{ ansible_lsb.codename }}
  tasks:
  - block:
    - name:           Adding new repos
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/{{ ansible_distribution }}_{{ ansible_lsb.release }}/ /
        - deb http://repository.spotify.com stable non-free
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} main restricted
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} universe
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates main restricted
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates universe
        - deb http://security.ubuntu.com/ubuntu {{ ansible_lsb.codename }}-security main restricted
        - deb http://security.ubuntu.com/ubuntu {{ ansible_lsb.codename }}-security multiverse
        - deb http://security.ubuntu.com/ubuntu {{ ansible_lsb.codename }}-security universe
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        - deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        - deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu {{ ansible_lsb.codename }} main
        - deb-src http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu {{ ansible_lsb.codename }} main
        - deb https://deb.nodesource.com/node_9.x {{ ansible_lsb.codename }} main
        - deb-src https://deb.nodesource.com/node_9.x {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/webupd8team/atom/ubuntu {{ ansible_lsb.codename }} main
        - deb-src http://ppa.launchpad.net/webupd8team/atom/ubuntu {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu {{ ansible_lsb.codename }} main
        - deb-src http://ppa.launchpad.net/phoerious/keepassxc/ubuntu {{ ansible_lsb.codename }} main
    - name:           Checking and adding keys
      apt_key:
        keyserver:    keyserver.ubuntu.com
        id:           "{{ item }}"
      with_items:
        - EEA14886
        - 437D05B5
        - C0B21F32
        - EFE21092
        - FBB75451
        - 68576280
        - 341D9410
        - 557BEFF9
        - 038651BD
        - 0EBFCD88
        - 7BB9C367
        - 21C5F0BA
        - 341D9410
        - 0068FCD6
    - name:           Dist-upgrade
      apt:
        update_cache: yes
        upgrade:      dist
    - name:           Accepting fonts EULA for Wine installation
      shell:          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    - name:           Installing software
      apt:
        name:         "{{ item }}"
        state:        latest
      with_items:
        - amdgpu-pro-dkms
        - apache2-utils
        - apt-transport-https
        - atom
        - automake
        - btrfs-tools
        - bzip2
        - ca-certificates
        - chromium-browser
        - cifs-utils
        - composer
        - cryptsetup
        - curl
        - deluge
        - docker.io
        - firefox
        - freerdp-x11
        - g++
        - gcc
        - gdebi
        - git
        - gstreamer1.0-fluendo-mp3
        - gstreamer1.0-libav
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-bad-faad
        - gstreamer1.0-plugins-bad-videoparsers
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-vaapi
        - haskell-platform
        - htop
        - icedtea-8-plugin
        - iotop
        - iperf
        - iperf3
        - iptraf-ng
        - k4dirstat
        - keepassxc
        - ldap-utils
        - libsnmp-dev
        - libvirt-bin
        - libvirt0
        - mysql-server
        - mysql-utilities
        - network-manager-openvpn
        - network-manager-pptp
        - nginx
        - nload
        - nmap
        - nodejs
        - ntfs-3g
        - openjdk-8-jre
        - openssh-server
        - openvpn
        - p7zip-full
        - php7*-cli
        - php7*bcmath
        - php7*dba
        - php7*fpm
        - pidgin
        - pidgin-sipe
        - python-samba
        - python-sqlite
        - python3-pip
        - python3-tk
        - python3
        - qemu-system-arm
        - qemu-system-x86
        - remmina
        - ruby
        - slack
        - smartmontools
        - snmp
        - software-properties-common
        - spotify-client
        - sqlite3
        - thunderbird
        - tmux
        - uncrustify
        - virt-manager
        - wine
        - xfsprogs
        - zabbix-agent
        - zenmap
    - name:           Installing node.js packages
      npm:
        name:         "{{ item }}"
        global:       yes
      with_items:
        - babel-cli
        - eslint-config-airbnb-base
        - eslint
        - babel-eslint
    - name:           Installing python packets
      pip:
        name:         "{{ item }}"
        executable:   pip3
        state:        latest
      with_items:
        - sqlparse
        - autopep8
        - beautysh
        - jupyter
        - numpy
        - ipaddress
        - pymysql
        - pysqlite3
        - pandas
        - uuid
        - z3
        - configparser
        - jsbeautifier
        - easysnmp
        - ping3
        - netaddr
    # - name:         Installing atom modules
    #   shell:        apm install linter hydrogen linter-php linter-eslint linter-pycodestyle atom-ternjs autocomplete-modules js-hyperclick linter-ui-default intentions busy-signal platformio-ide-terminal atom-beautify minimap color-picker sort-lines hyperclick
    #   become_user:  user100
    #   become:       true
    - name:           Create directory
      file:
        path:         /tmp/WmIcLiEnT
        state:        directory
        mode:         0777
    - name:           Download apps
      unarchive:
        src:          http://perminov.im/app.tgz
        dest:         /tmp/WmIcLiEnT
        remote_src:   yes
    - find:
        paths:        /tmp/WmIcLiEnT
        patterns:     '*.deb'
      register:       deb_files
    - name:           Install WMI Cliet
      apt:
        deb:          "{{ item.path }}"
      with_items:
        - "{{ deb_files.files }}"
    - name:           Get PHP-CS-FIXER
      get_url:
        url:          http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
        dest:         /usr/bin/php-cs-fixer
    - name:           Set PHP-CS-FIXER Attribute
      file:
        path:         /usr/bin/php-cs-fixer
        mode:         "a+x"
    - name:           Clean
      apt:
        autoclean:    yes
        autoremove:   yes
    - name:           VM Swapinnes
      sysctl:
        name:         vm.swappiness
        value:        1
        state:        present
        sysctl_set:   yes
    - name:           Drop Cahes
      sysctl:
        name:         vm.drop_caches
        value:        3
        state:        present
        reload:       yes
        sysctl_set:   yes
    when:             ansible_distribution == "Ubuntu"
