- hosts:              localhost
  gather_facts:       yes
  strategy:           free
  become:             yes
  become_method:      sudo
  tasks:
  - block:
    - name:           Disable SELINUX
      selinux:
        state:        disabled
    - name:           Download atom
      get_url:
        url:          https://atom.io/download/rpm
        dest:         /tmp/atom.rpm
    - name:           Set PHP-CS-FIXER Attribute
      file:
        path:         /usr/bin/php-cs-fixer
        mode:         "a+x"
    - name:           VM Swapinnes
      sysctl:
        name:         vm.swappiness
        value:        1
        state:        present
        reload:       yes
        sysctl_set:   yes
    - name:           Drop Cahes
      sysctl:
        name:         vm.drop_caches
        value:        3
        state:        present
        reload:       yes
        sysctl_set:   yes
<<<<<<< HEAD
    - name:           FS inotify
      sysctl:
        name:         fs.inotify.max_user_watches
        value:        524288
=======
  - block:
    - name:           Adding new Ubuntu repos
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/{{ ansible_distribution }}_{{ ansible_lsb.release }}/ /
        - deb http://repository.spotify.com stable non-free
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        - deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        - deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu {{ ansible_lsb.codename }} main
        - deb https://deb.nodesource.com/node_9.x {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/webupd8team/atom/ubuntu {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu {{ ansible_lsb.codename }} main
    - name:           Adding work ubuntu repository
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }} main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }} multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }} universe
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-updates main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-updates multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-updates universe
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-security main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-security multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-security universe
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} main restricted
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} universe
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates main restricted
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates universe
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security main restricted
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security universe
      when:           ansible_env.HOSTNAME.find('ies-holding') == 1
    - name:           Adding home ubuntu repository
      apt_repository:
        repo:         "{{ item }}"
>>>>>>> 69b7be57735f3a9a1feb1957ee89e0d3b397f2e1
        state:        present
        reload:       yes
        sysctl_set:   yes
  - block:
    - name:           Negativo repository
      yum_repository:
        name:         negativo_17
        description:  Bumblebee and Nvidia drivers
        baseurl:      https://negativo17.org/repos/nvidia/fedora-$releasever/$basearch/
        enabled:      yes
        gpgkey:       https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    - name:           Docker repo
      yum_repository:
        name:         docker-ce-stable
        description:  Docker CE Stable - $basearch
        baseurl:      https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        enabled:      yes
        gpgkey:       https://download.docker.com/linux/fedora/gpg
    - name:           Chrome repo
      yum_repository:
        name:         chrome
        description:  google-chrome
        baseurl:      http://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled:      yes
        gpgkey:       https://dl-ssl.google.com/linux/linux_signing_key.pub
    - name:           Install RPM FUSION free
      dnf:
        name:         https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-27.noarch.rpm
        state:        present
    - name:           Install RPM FUSION non-free
      dnf:
        name:         https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-27.noarch.rpm
        state:        present
    - name:           Node repo
      shell:          "curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -"
    - name:           Install atom
      dnf:
        name:         /tmp/atom.rpm
        state:        present
    - name:           Install packets
      dnf:
        name:         "{{ item }}"
        state:        latest
      with_items:
        - python-smbc
        - httpd-tools
        - btrfs-progs
        - bzip2
        - chromium
        - cifs-utils
        - cryptsetup
        - curl
        - deluge-gtk
        - docker-ce
        - firefox
        - git
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-free-gtk
        - gstreamer1-plugins-base
        - gstreamer1-plugins-good
        - gstreamer1-plugins-ugly-free
        - libva-vdpau-driver
        - ghc-compiler
        - htop
        - golang
        - icedtea-web
        - iotop
        - iperf3
        - iptraf-ng
        - keepassxc
        - nload
        - nmap
        - nodejs
        - ntfs-3g
        - java-1.8.0-openjdk
        - openssh-server
        - openvpn
        - p7zip
        - p7zip-plugins
        - p7zip-gui
        - python-sqlite3dbm
        - python3-pip
        - python3-tkinter
        - python3
        - ruby
        - smartmontools
        - net-snmp
        - sqlite
        - tmux
        - uncrustify
        - wine
        - xfsprogs
        - zabbix-agent
        - nmap-frontend
        - akmod-bbswitch
        - bumblebee
        - primus
        - nvidia-driver
        - kernel-devel
        - akmod-nvidia
        - dkms
        - acpi
        - google-chrome-stable
    - name:           Installing node.js packages
      npm:
        name:         "{{ item }}"
        global:       yes
      with_items:
        - babel-cli
        - eslint-config-airbnb-base
        - eslint
        - babel-eslint
    - name:           Installing python packets
      pip:
        name:         "{{ item }}"
        executable:   pip3
        state:        latest
      with_items:
        - sqlparse
        - autopep8
        - beautysh
        - jupyter
        - numpy
        - ipaddress
        - pymysql
        - pysqlite3
        - pandas
        - uuid
        - z3
        - configparser
        - jsbeautifier
        - ping3
        - netaddr
    - name:         Installing atom modules
      shell:        sudo -u user100 apm install linter hydrogen linter-php linter-eslint linter-pycodestyle atom-ternjs autocomplete-modules js-hyperclick linter-ui-default intentions busy-signal platformio-ide-terminal atom-beautify minimap color-picker sort-lines hyperclick go-plus language-protobuf
    - name: Docker enable and startup
      systemd:
        name: docker
        enabled: yes
        state: started
        masked: no
    - name: Docker swarm init
      shell: "docker swarm init"
    - name: Restart
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true
