- hosts:              all
  gather_facts:       yes
  strategy:           free
  become:             yes
  become_method:      sudo
  tasks:
  - block:
    - name:           Create directory
      file:
        path:         /tmp/WmIcLiEnT
        state:        directory
        mode:         0777
    - name:           Download apps
      unarchive:
        src:          http://perminov.im/app.tgz
        dest:         /tmp/WmIcLiEnT
        remote_src:   yes
    - name:           Get PHP-CS-FIXER
      get_url:
        url:          http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
        dest:         /usr/bin/php-cs-fixer
    - name:           Set PHP-CS-FIXER Attribute
      file:
        path:         /usr/bin/php-cs-fixer
        mode:         "a+x"
    - name:           VM Swapinnes
      sysctl:
        name:         vm.swappiness
        value:        1
        state:        present
        sysctl_set:   yes
    - name:           Drop Cahes
      sysctl:
        name:         vm.drop_caches
        value:        3
        state:        present
        reload:       yes
        sysctl_set:   yes
  - block:
    - name:           Adding new Ubuntu repos
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/{{ ansible_distribution }}_{{ ansible_lsb.release }}/ /
        - deb http://repository.spotify.com stable non-free
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        - deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        - deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu {{ ansible_lsb.codename }} main
        - deb https://deb.nodesource.com/node_9.x {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/webupd8team/atom/ubuntu {{ ansible_lsb.codename }} main
        - deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu {{ ansible_lsb.codename }} main
    - name:           Adding work ubuntu repository
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }} main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }} multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }} universe
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-updates main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-updates multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-updates universe
        - deb [arch=amd64] http://10.53{{ ansible_distribution }} == 'Ubuntu' and.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-security main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-security multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com/ {{ ansible_lsb.codename }}-security universe
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} main restricted
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} universe
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates main restricted
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates universe
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security main restricted
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security multiverse
        - deb [arch=i386] http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security universe
      when:           ansible_env.HOSTNAME.find('ies-holding') == 1
    - name:           Adding home ubuntu repository
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-backports main restricted universe multiverse
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} main restricted
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} multiverse
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} universe
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates main restricted
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates multiverse
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-updates universe
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security main restricted
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security multiverse
        - deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }}-security universe
      when:           ansible_env.HOSTNAME  == book02
    - name:           Checking and adding keys
      apt_key:
        keyserver:    keyserver.ubuntu.com
        id:           "{{ item }}"
      with_items:
        - EEA14886
        - 437D05B5
        - C0B21F32
        - EFE21092
        - FBB75451
        - 68576280
        - 341D9410
        - 557BEFF9
        - 038651BD
        - 0EBFCD88
        - 7BB9C367
        - 21C5F0BA
        - 341D9410
        - 0068FCD6
    - name:           Dist-upgrade
      apt:
        update_cache: yes
        upgrade:      dist
    - name:           Accepting fonts EULA for Wine installation
      shell:          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    - name:           Installing software
      apt:
        name:         "{{ item }}"
        state:        latest
      with_items:
        - apache2-utils
        - apt-transport-https
        - atom
        - automake
        - btrfs-tools
        - bzip2
        - ca-certificates
        - chromium-browser
        - cifs-utils
        - composer
        - cryptsetup
        - curl
        - deluge
        - docker.io
        - firefox
        - freerdp-x11
        - g++
        - gcc
        - gdebi
        - git
        - gstreamer1.0-fluendo-mp3
        - gstreamer1.0-libav
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-bad-faad
        - gstreamer1.0-plugins-bad-videoparsers
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-vaapi
        - haskell-platform
        - htop
        - icedtea-8-plugin
        - iotop
        - iperf
        - iperf3
        - iptraf-ng
        - k4dirstat
        - keepassxc
        - ldap-utils
        - libsnmp-dev
        - libvirt-bin
        - libvirt0
        - mysql-server
        - mysql-utilities
        - network-manager-openvpn
        - network-manager-pptp
        - nginx
        - nload
        - nmap
        - nodejs
        - ntfs-3g
        - openjdk-8-jre
        - openssh-server
        - openvpn
        - p7zip-full
        - php7*-cli
        - php7*bcmath
        - php7*dba
        - php7*fpm
        - pidgin
        - pidgin-sipe
        - python-samba
        - python-sqlite
        - python3-pip
        - python3-tk
        - python3
        - qemu-system-arm
        - qemu-system-x86
        - remmina
        - ruby
        - slack
        - smartmontools
        - snmp
        - software-properties-common
        - spotify-client
        - sqlite3
        - thunderbird
        - tmux
        - uncrustify
        - virt-manager
        - wine
        - xfsprogs
        - zabbix-agent
        - zenmap
    - find:
        paths:        /tmp/WmIcLiEnT
        patterns:     '*.deb'
      register:       deb_files
    - name:           Install WMI Cliet deb
      apt:
        deb:          "{{ item.path }}"
      with_items:
        - "{{ deb_files.files }}"
    - name:           Clean
      apt:
        autoclean:    yes
        autoremove:   yes
    when:             ansible_distribution == "Ubuntu"
  - block:
    - name:           remove repos
      file:
        path:         /etc/yum.repos.d
        state:        absent
    - name:           Create folder
      file:
        path:         /etc/yum.repos.d
        state:        directory
    - name:           Adding repos
      yum_repository:
        file:         t_repos
        description:  Some repo
        name:         "{{ item.name }}"
        baseurl:      "{{ item.baseurl }}"
        enabled:      yes
        gpgcheck:     no
      with_items:
        - name:       node.js
          baseurl:    https://rpm.nodesource.com/pub_9.x/el/7/x86_64/
        - name:       atom
          baseurl:    https://copr-be.cloud.fedoraproject.org/results/mosquito/atom/epel-7-$basearch/
        - name:       atomic
          baseurl:    http://10.53.12.250/centos/atomic/7/x86_64/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY.art.txt
        - name:       base
          baseurl:    http://10.53.12.250/centos/$releasever/os/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - name:       updates
          baseurl:    http://10.53.12.250/centos/$releasever/updates/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - name:       extras
          baseurl:    http://10.53.12.250/centos/$releasever/extras/$basearch/
          gpgcheck:   1
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - name:       centosplus
          baseurl:    http://10.53.12.250/centos/$releasever/centosplus/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - name:       cr
          baseurl:    http://10.53.12.250/centos/$releasever/cr/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - name:       fasttrack
          baseurl:    http://10.53.12.250/centos/$releasever/fasttrack/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - name:       elrepo
          baseurl:    http://10.53.12.250/centos/elrepo/elrepo/el7/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
        - name:       elrepo-extras
          baseurl:    http://10.53.12.250/centos/elrepo/extras/el7/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
        - name:       epel
          baseurl:    http://10.53.12.250/centos/epel/7/$basearch
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        - name:       ius
          baseurl:    http://10.53.12.250/centos/ius/stable/CentOS/7/$basearch
          gpgkey:     file:///etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
        - name:       nux-dextop
          baseurl:    http://10.53.12.250/centos/nux/dextop/el7/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro
        - name:       rpmfusion-free-updates
          baseurl:    http://10.53.12.250/centos/rpmfusion/free/el/updates/7/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7
        - name:       rpmfusion-free-updates-debuginfo
          baseurl:    http://10.53.12.250/centos/rpmfusion/free/el/updates/7/$basearch/debug/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7
        - name:       rpmfusion-nonfree-updates
          baseurl:    http://10.53.12.250/centos/rpmfusion/nonfree/el/updates/7/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-7
        - name:       rpmfusion-nonfree-updates-debuginfo
          baseurl:    http://10.53.12.250/centos/rpmfusion/nonfree/el/updates/7/$basearch/debug/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-7
        - name:       zabbix
          baseurl:    http://10.53.12.250/centos/zabbix/3.0/rhel/7/$basearch/
          gpgkey:     file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
        - name:       keepassxc
          baseurl:    https://copr-be.cloud.fedoraproject.org/results/bugzy/keepassxc/epel-7-$basearch/
          gpgkey:     https://copr-be.cloud.fedoraproject.org/results/bugzy/keepassxc/pubkey.gpg
    - name:           Install dev tools
      yum:
        name:         "@Development tools"
        state:        present
    - name:           Install packets
      yum:
        name:         "{{ item }}"
        state:        latest
      with_items:
        - python-smbc
        - httpd-tools
        - btrfs-progs
        - bzip2
        - chromium
        - cifs-utils
        - cryptsetup
        - curl
        - deluge-gtk
        - docker
        - firefox
        - freerdp
        - git
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-free-gtk
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-base
        - gstreamer1-plugins-base-tools
        - gstreamer1-plugins-good
        - gstreamer1-plugins-ugly
        - gstreamer1-vaapi
        - gstreamer1-libav
        - ghc-compiler
        - htop
        - icedtea-web
        - iotop
        - iperf
        - iperf3
        - iptraf-ng
        - keepassxc
        - php72u-process
        - openldap-clients
        - net-snmp-devel
        - libvirt
        - mariadb-server
        - mysql-utilities
        - NetworkManager-openvpn-gnome
        - NetworkManager-pptp-gnome
        - nginx
        - nload
        - nmap
        - nodejs
        - ntfs-3g
        - java-1.8.0-openjdk
        - openssh-server
        - openvpn
        - p7zip
        - p7zip-plugins
        - p7zip-gui
        - php72u-cli
        - php72u-bcmath
        - php72u-dba
        - php72u-fpm
        - pidgin
        - pidgin-sipe
        - python-sqlite3dbm
        - python36u-pip
        - python36u-tkinter
        - python36u
        - qemu-system-arm
        - qemu-system-x86
        - remmina
        - remmina-plugins-rdp
        - ruby
        - smartmontools
        - net-snmp
        - sqlite
        - thunderbird
        - tmux
        - uncrustify
        - virt-manager
        - wine
        - xfsprogs
        - zabbix-agent
        - nmap-frontend
        - wmi
    - find:
        paths:        /tmp/WmIcLiEnT
        patterns:     '*.rpm'
      register:       rpm_files
    - name:           Install WMI Cliet rpm
      yum:
        name:         "{{ item.path }}"
        state:        present
      with_items:
        - "{{ rpm_files.files }}"
    when:             ansible_os_family == "RedHat"


  - block:
    - name:           Installing node.js packages
      npm:
        name:         "{{ item }}"
        global:       yes
      with_items:
        - babel-cli
        - eslint-config-airbnb-base
        - eslint
        - babel-eslint
    - name:           Installing python packets
      pip:
        name:         "{{ item }}"
        executable:   pip3
        state:        latest
      with_items:
        - sqlparse
        - autopep8
        - beautysh
        - jupyter
        - numpy
        - ipaddress
        - pymysql
        - pysqlite3
        - pandas
        - uuid
        - z3
        - configparser
        - jsbeautifier
        - ping3
        - netaddr
    - name:           Installing atom modules
      shell:          apm install linter hydrogen linter-php linter-eslint linter-pycodestyle atom-ternjs autocomplete-modules js-hyperclick linter-ui-default intentions busy-signal platformio-ide-terminal atom-beautify minimap color-picker sort-lines hyperclick
      become_user:    user100
      become:         true
