- hosts:              all
  gather_facts:       yes
  strategy:           free
  become:             yes
  become_method:      sudo
  tasks:
  - block:
    - name:           Download node repos setup file and latest atom editor
      get_url:
        url:          "{{ item }}"
        dest:         /tmp/
      with_items:
        - https://deb.nodesource.com/setup_8.x
        - https://atom.io/download/deb
    - name:           Installing node repos
      shell:          bash /tmp/setup_8.x
    - name:           Removing old repos
      apt_repository:
        repo:         "{{ item }}"
        state:        absent
      with_items:
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial main restricted
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial universe
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
        - deb http://ru.archive.ubuntu.com/ubuntu/ xenial-updates universe
        - deb http://security.ubuntu.com/ubuntu xenial-security main restricted
        - deb http://security.ubuntu.com/ubuntu xenial-security multiverse
        - deb http://security.ubuntu.com/ubuntu xenial-security universe
    - name:           Adding new repos
      apt_repository:
        repo:         "{{ item }}"
        state:        present
      with_items:
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-updates main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial universe
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-updates universe
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-updates multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-backports main restricted universe multiverse
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-security main restricted
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-security universe
        - deb [arch=amd64] http://10.53.12.250/ru.archive.ubuntu.com xenial-security multiverse
        - deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /
        - deb http://repository.spotify.com stable non-free
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial main restricted
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-updates main restricted
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial universe
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-updates universe
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial multiverse
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-updates multiverse
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-backports main restricted universe multiverse
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-security main restricted
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-security universe
        - deb [arch=i386] http://mirror.yandex.ru/ubuntu xenial-security multiverse
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        - deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        - ppa:ansible/ansible
    - name:           Checking and adding keys
      apt_key:
        keyserver:    keyserver.ubuntu.com
        id:           "{{ item }}"
      with_items:
        - 341D9410
        - D2C19886
        - 557BEFF9
        - C0B21F32
        - EFE21092
        - FBB75451
        - 341D9410
        - 437D05B5
    - name:           Installing docker key
      apt_key:
        url:          https://download.docker.com/linux/ubuntu/gpg
        state:        present
    - name:           Dist-upgrade
      apt:
        update_cache: yes
        upgrade:      dist
    - name:           Accepting fonts EULA for Wine installation
      shell:          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    - name:           Installing software
      apt:
        name:         "{{ item }}"
        state:        present
      with_items:
        - nmap
        - wine
        - zenmap
        - firefox
        - chromium-browser
        - g++
        - gcc
        - nodejs
        - git
        - iotop
        - htop
        - iperf
        - ldap-utils
        - iperf3
        - iptraf-ng
        - python3.5
        - mysql-server
        - mysql-utilities
        - nginx
        - zabbix-agent
        - apache2-utils
        - smartmontools
        - openjdk-8-jre
        - icedtea-8-plugin
        - thunderbird
        - automake
        - btrfs-tools
        - bzip2
        - cifs-utils
        - gdebi
        - k4dirstat
        - python3-pip
        - php7.0-cli
        - gstreamer1.0-libav
        - gstreamer1.0-fluendo-mp3
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-bad-videoparsers
        - gstreamer1.0-plugins-bad-faad
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-vaapi
        - docker.io
        - apt-transport-https
        - software-properties-common
        - pidgin
        - pidgin-sipe
        - ntfs-3g
        - nload
        - p7zip-full
        - openvpn
        - network-manager-openvpn
        - network-manager-pptp
        - sqlite3
        - snmp
        - qemu-system-arm
        - qemu-system-x86
        - libvirt0
        - libvirt-bin
        - virt-manager
        - python-samba
        - python-sqlite
        - python*pip
        - php7.0-bcmath
        - php7.0-dba
        - php7.0-fpm
        - tmux
        - xfsprogs
        - cryptsetup
        - spotify-client
        - freerdp-x11
        - remmina
        - deluge
    - name:           Installing atom
      apt:
        deb:          '/tmp/atom-amd64.deb'
      register:       nano
    - debug:          msg="{{nano}}"
    when:             ansible_distribution_version == "16.04"
  - block:
    - name:           Installing node.js packages
      npm:
        name:         "{{ item }}"
        global:       yes
      with_items:
        - babel-cli
        - eslint-config-airbnb-base
        - eslint
        - babel-eslint
    - name:           Installing python packets
      pip:
        name:         "{{ item }}"
        executable:   pip3
      with_items:
        - autopep8
        - beautysh
    - name:           Installing atom modules
      shell:          "apm install {{ item }}"
      with_items:
        - linter
        - linter-php
        - linter-eslint
        - linter-pycodestyle
        - atom-ternjs
        - autocomplete-modules
        - js-hyperclick
        - linter-ui-default
        - intentions
        - busy-signal
        - platformio-ide-terminal
        - atom-beautify
        - minimap
        - color-picker
        - sort-lines
        - hyperclick
      become_user:    user100
      become:         true
